### ISSUE TITLE
Support for Yarn berry pnp repos

### ISSUE THREAD

**Issue by ericcater** [gperdomor/nx-tools#1064]
I'm trying to use @nx-tools/nx-container with yarn v4.3.0 with pnp install mode. Fails because PackageLoader only checks node_modules for a given package (@nx-tools/container-metadata in my case)

![image](https://github.com/gperdomor/nx-tools/assets/82330234/340ee64f-29d2-4ee1-8044-4735c2cddb74)

I believe there's a pnpapi to check if pnp packages are installed.

**Comment by Nelfimov** [comment]
`@nx-tools/container-metadata` also needs adjustments in `packageExtensions`, but it doesn't show when running nx commands. You can debug like this:

```sh
yarn node -e "import('@nx-tools/container-metadata').then(m=>console.log('ok')).catch(e=>console.error(e))"
```

What worked for me:
- add `@nx-tools/container-metadata` in root package.json
- adjust `packageExtensions` like this
  ```yaml
  packageExtensions:
    '@nx-tools/container-metadata@*':
      dependencies:
        tslib: '*'
        '@nx/devkit': '*'
  ```
