### ISSUE TITLE
Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by mattndr** [gperdomor/nx-tools#349]
Hi, I'm trying to use this setup for build and push Docker image. The github workflow fails if I enable metadata.
If I remove metadata form this configuration, the workflow works correctly.

**angular.json**
```
"docker": {
  "executor": "@nx-tools/nx-docker:build",
  "options": {
    "file": "./Dockerfile.api.prod",
    "buildArgs": [
      "NODE_VERSION=14.17.5"
    ],
    "target": "builded",
    "noCache": true,
    "push": true,
    "meta": {
      "enabled": true,
      "images": ["mattndr/webapp1-api"],
      "tags": [
        "type=sha,prefix=sha-"
      ]
    }
  }
}
```
**Workflow** 
```
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 'Install Dependencies'
        run: npm i

      - name: 'nx build'
        run: npx nx affected --target=docker --all
```

**Workflow error**
```
> nx run api:docker 
Parameter token or opts.auth is required

———————————————————————————————————————————————

>  NX   ERROR  Running target "docker" failed

  Failed tasks:
  
  - api:docker
  
  You can isolate the above projects by passing: --only-failed

Error: Process completed with exit code 1.
```
