### ISSUE TITLE
Cache export feature not supported

### ISSUE THREAD

**Issue by idanamit** [gperdomor/nx-tools#476]
I'm new to NX and I've been trying to define a github action to create and publish a docker image using the nx-docker tool.

I'm using the local cache option and I'm receiving the following error when using the nx-docker target from my Github action .yml file:
`error: cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")`

When I'm using the [docker-build-push action](https://github.com/marketplace/actions/build-and-push-docker-images) it works fine with my configuration.

My action job definition looks like this:
```
publish-dev-image:
    name: Publish Dev Image
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.DOCKER_DEV_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build code
        run: yarn nx run api:docker
        env:
          INPUT_TAGS: ${env.TAG}
          INPUT_CACHE_FROM: type=local,src=/tmp/.buildx-cache
          INPUT_CACHE_TO: type=local,dest=/tmp/.buildx-cache-new,mode=max
          INPUT_PUSH: true
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

```

the docker executor in the project.json file is defined as follows:
```
"docker": {
      "executor": "@nx-tools/nx-docker:build"
    }
```

Am I doing something wrong?
Please tell me of you need me to provide additional data
