### ISSUE TITLE
Can't pass --secret to a Dockerfile

### ISSUE THREAD

**Issue by Rikazavr** [gperdomor/nx-tools#595]
Hello!

I'm trying to pass a `--secret` to my Dockerfile, here is my project.json
```
    "docker": {
      "executor": "@nx-tools/nx-docker:build",
      "options": {
        "push": true,
        "secrets": [
          "npm_token=${{ secrets.NPM_TOKEN }}"
        ],
        "metadata": {
          ...
        }
      }
    },
```
In build.yaml
```
      - run: npx nx affected --target=docker
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TAGS: ${{ steps.meta.outputs.tag }}
```
And in Dockerfile
```
RUN --mount=type=secret,id=npm_token \
  echo "//verdaccio-uchi.runit.cc/:_authToken=$(cat /run/secrets/npm_token)" >> .npmrc
```

But my build fails
```
#19 4.271 npm ERR! code E401
#19 4.273 npm ERR! Unable to authenticate, your authentication token seems to be invalid.
```

What am I doing wrong?
Maybe my syntax is not wright?
`"npm_token=${{ secrets.NPM_TOKEN }}"`

![Снимок экрана 2022-07-27 в 18 44 27](https://user-images.githubusercontent.com/7078454/181310304-d5fa5b18-7759-4e5f-a7ac-197742d8d60f.png)

**Comment by Radiergummi** [comment]
Did you get this to work eventually?

**Comment by Rikazavr** [comment]
> Did you get this to work eventually?

Yes! This worked, if I remember correctly
```
      - run: npx nx affected --target=docker
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TAGS: ${{ steps.meta.outputs.tag }}
          INPUT_SECRETS: 'npm_token=${{ secrets.NPM_TOKEN }}'
```

And my project.json looks like this now
```
    "docker": {
      "executor": "@nx-tools/nx-docker:build",
      "options": {
        "push": true,
        "metadata": {
          "images": ["..."],
          "load": true,
          "tags": [
            "type=schedule",
            ...
          ]
        }
      }
    },
```
