### ISSUE TITLE
[@nx-tools/docker] Passing metadata options through environment variables

### ISSUE THREAD

**Issue by arielweinberger** [gperdomor/nx-tools#619]
Hi,

Thanks for this fantastic set of tools. We need to make use of metadata options, and these are distinct in our CI setup, depending on the branch the user is on etcetera. So they need to be customizable in our GitHub Action.

I was able to provide various configuration options via `INPUT_*`, but I cannot figure out how to make it work for metadata options.

For example, I've tried `INPUT_METADATA_TAGS=...` but this does not get picked up.

Is there anything I am missing? Is the answer perhaps in the undocumented `@nx-tools/docker-metadata` package in this repo?

Any feedback/help is appreciated. Thanks!

**Comment by gperdomor** [comment]
@arielweinberger INPUT_TAGS should works... can you share the repo or the project.json config please

**Comment by arielweinberger** [comment]
Hey @gperdomor thanks for taking a look. I am aware that `INPUT_TAGS` works, but I need the metadata variables, these ones:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/4976416/195655075-4c4cc749-a91f-4933-8d6f-dc11c035274f.png">

What I ended up doing is using a separate GitHub workflow job step to output the tags based on metadata, and import them into my dockerization executor.

```yml
      # https://github.com/docker/metadata-action
      - name: Docker Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: "407256539111.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.project }}-nx-test"
          tags: |
            type=sha,prefix=sha-
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
      - name: Dockerize
        run: npx nx run-many --target docker:build --projects=${{ matrix.project }}
        env:
          # https://www.npmjs.com/package/@nx-tools/nx-docker
          INPUT_TAGS: ${{ steps.meta.outputs.tags }}
          INPUT_PUSH: true
```

**Comment by gperdomor** [comment]
:o ok ok... Well in first place you not need to use the `docker/metadata-action`, nx tools handles that for you, the only requirement is to setup the metadata.images directly in your project.json

```
{
  "name": "api",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/api/src",
  "projectType": "application",
  "targets": {
    "build": { ... },
    "serve": { ... },
    "lint": { ... },
    "test": { ... },
    "docker": {
      "executor": "@nx-tools/nx-docker:build",
      "options": {
        "metadata": {
          "images": ["arielweinberger/api"], <-- THIS IS REQUIRED for the automatic metadata flow, don't worry about the value, can be overriden with INPUT_IMAGES or with INPUT_API_IMAGES (because the name of the project is api)
          "tags": [
            "type=sha,prefix=sha-",
            "type=ref,event=branch",
            "type=ref,event=pr",
            "type=ref,event=tag"
          ]
        }
      }
    }
  }
}
```

All accepted env variables for metadata are: INPUT_BAKE_TARGET, INPUT_GITHUB_TOKEN, INPUT_SEP_LABELS, INPUT_SEP_TAGS, INPUT_FLAVOR, INPUT_IMAGES, INPUT_LABELS, INPUT_TAGS, and the "prefixed" alternatives with the name of the project like INPUT_(PROJECT)_IMAGES, etc...

With the prefixed alternatives you can build everything without a matrix:

```
      - name: Dockerize
        run:  npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=docker --parallel=2
        env:
          // Common vars
          INPUT_PUSH: true
          // Specific for each project
          INPUT_API_TAGS: 407256539111.dkr.ecr.us-east-1.amazonaws.com/api-nx-test
          INPUT_WEB_TAGS: 407256539111.dkr.ecr.us-east-1.amazonaws.com/web-nx-test
          INPUT_GATEWAY_TAGS: 407256539111.dkr.ecr.us-east-1.amazonaws.com/gateway-nx-test
          
```
