### ISSUE TITLE
Push to heroku registry fail - 405 Method Not Allowed

### ISSUE THREAD

**Issue by luca-montaigut** [gperdomor/nx-tools#728]
Hello, a buildkit update prevents pushing on the heroku registry.

Here's what I got from support:
https://help.heroku.com/74S3XXMP/workaround-for-docker-push-error-405-method-not-allowed-using-buildkit-0-11

It seems that the problem comes from the "provenance" option. I don't know if I can do anything else to help but I thought I could at least get you the information.

**Comment by na-ji** [comment]
Hello!
It would be great to have a way to disable provenance attestation on the configuration. I tried to use the env variable `BUILDX_NO_DEFAULT_ATTESTATIONS` but it didn't work for me. Any idea other than to downgrade buildx?

**Comment by thisismydesign** [comment]
This works:
```
- name: Docker build
  uses: docker/build-push-action@v3
  with:
    provenance: false
```
