### ISSUE TITLE
`@nx-tools/container-metadata `Metadata tags not working in GitHub Actions

### ISSUE THREAD

**Issue by arielweinberger** [gperdomor/nx-tools#758]
Hi,

I have installed both `@nx-tools/container` and `@nx-tools/container-metadata` and configured my build target like so:

```json
"docker:build": {
  "executor": "@nx-tools/nx-container:build",
  "options": {
          "tags": ["xxx.dkr.ecr.us-east-1.amazonaws.com/xxx"],
          "push": true,
          "platforms": ["linux/amd64"],
          "metadata": {
            "tags": [
              "type=schedule",
              "type=ref,event=branch",
              "type=ref,event=tag",
              "type=ref,event=pr",
              "type=semver,pattern={{version}}",
              "type=semver,pattern={{major}}.{{minor}}",
              "type=semver,pattern={{major}}",
              "type=sha"
            ]
  }
}
```

Running the target locally works just fine. When running via GitHub Actions:

```
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerize
        run: npx nx run-many --target=docker:build --configuration=ci --all --parallel --maxParallel=3
        env:
          INPUT_GITHUB_SECRET: ${{ secrets.GITHUB_TOKEN }}
```

The image is built and pushed to AWS ECR successfully, but it appears as `<untagged>`.

For reference, using the [docker/metadata-action](https://github.com/docker/metadata-action) action works just fine, so I am not sure what I am missing.

This is how I would normally use the abovementioned GitHub action:
```
      - name: Docker Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: "xxx.dkr.ecr.us-east-1.amazonaws.com/xxx"
          tags: |
            type=sha,prefix=sha-
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-
            type=ref,event=tag,prefix=tag-
            type=raw,value=${{ github.run_id }},prefix=gh-
```

Help would be appreciated, I'd really like to use this tool. Thanks!
