### ISSUE TITLE
Workaround for --privileged on Bitbucket pipelines?

### ISSUE THREAD

**Issue by Divaaan** [gperdomor/nx-tools#789]
Hi, any idea how to get around the following?

` NX   buildx failed with: ERROR: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed`

I've tried search, some suggested you set the ```DOCKER_BUILDKIT=0``` but no luck as Bitbucket doesn't allow the use of `--privileged`

Any suggestions would be greatly appreciated.

**Comment by gperdomor** [comment]
@Divaaan try with `DOCKER_BUILDKIT=0 nx run your-app:container-target` or similar... Or try with the Podman engine and let me know if works :D

**Comment by Divaaan** [comment]
@gperdomor Champ! Thanks for the quick reply, will have a try and let you know 👌🏼

**Comment by gperdomor** [comment]
@Divaaan Yes, podman should be installed in the environment...

I provide 3 images (for docker, podman and kaniko) to run the build inside Gitlab CI, you can check the example of usage here https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/docs/ci/gitlab-ci.md

I did't test it in bitbucket but in theory should works too

**Comment by Divaaan** [comment]
@gperdomor Thanks for the info. Still a bit unsure on what you mean by podman needing to be installed in the environment?
Because using the image you provide, the step above runs the command inside it or am I missing something 🤔 
I checked the example but see nowhere that podman is being installed and looks to be already installed? Might be wrong here.

**Comment by gperdomor** [comment]
The provided image already has Podman installed, so you can skip that step... but the default image used by bitbucket pipelines not, that is why you are getting the Podman error

**Comment by gperdomor** [comment]
I'm not a bitbucket user but I will try to create a repo tomorrow to try to help you 😅

**Comment by Divaaan** [comment]
@gperdomor Ah okay that makes sense! Can you maybe explain as well what makes your `nx-docker` image different from using another image for example? Does it have additional packages etc installed needed for the build?

**Comment by gperdomor** [comment]
@Divaaan all the images contains node, yarn, npm, pnpm, git, other common tools and docker, podman or kaniko

**Comment by tomaszkrzyzanowski** [comment]
Maybe someone will benefit, as I was able to run nx-container with Kaniko on Bitbucket Pipelines

```yaml
- step:
    name: Build docker images
    image: gperdomor/nx-kaniko:20.11.0-alpine
    script:
      - export INPUT_ENGINE=kaniko
      - export INPUT_PUSH=true
      - NX_HEAD=$BITBUCKET_COMMIT
      # Login to registry
      - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n $DH_USER:$DH_PASS | base64)\"}}}" > /kaniko/.docker/config.json
      - npx nx affected --target=build-docker --base="origin/main" --head=HEAD --configuration=production  --parallel=1
```
